image: fedora:28

stages:
  - build

before_script:
  - dnf update -y
  - dnf install -y desktop-file-utils gettext glib2-devel gobject-introspection-devel gtk3-devel intltool itstool python3-devel python2-pep8 libappstream-glib libwnck3 python2-gobject python3-gobject make yelp-tools

# TODO: split Python 2 and Python 3 builds entirely (or, better, require Python
# 3). The tests are hardcoded to run Python 2...
build:
  stage: build
  script:
    - PYTHON=python3 ./autogen.sh
    - make
    - make check
  artifacts:
    when: on_failure
    name: "d-feet-${CI_COMMIT_REF_NAME}-${CI_JOB_NAME}"
    paths:
      - "${CI_PROJECT_DIR}/src/tests/test-suite.log"
      - "${CI_PROJECT_DIR}/help/Makefile"
