include: 'https://gitlab.gnome.org/GNOME/citemplates/raw/master/flatpak/flatpak_ci_initiative.yml'


variables:
    BUNDLE: "dfeet-git.flatpak"

fedora:
    stage: test
    image: fedora:rawhide
    before_script:
        - dnf update -y
        - dnf install -y desktop-file-utils dbus-daemon gettext glib2-devel gobject-introspection-devel gtk3-devel intltool itstool meson ninja-build python3-devel python3-pycodestyle libappstream-glib libwnck3 python3-gobject python3-gobject make yelp-tools xorg-x11-server-Xvfb
    script:
        - meson _build
        - ninja -C _build
        - mkdir -p /run/dbus
        - mkdir -p /var
        - ln -s /var/run /run
        - dbus-daemon --system --fork
        - xvfb-run -a -s "-screen 0 1024x768x24" ninja -C _build test
    artifacts:
        when: on_failure
        name: "d-feet-${CI_COMMIT_REF_NAME}-${CI_JOB_NAME}"
        paths:
            - "${CI_PROJECT_DIR}/_build/meson-logs/testlog.txt"


flatpak:
    extends: .flatpak
    variables:
        GIT_SUBMODULE_STRATEGY: normal

        # Replace with your manifest path
        MANIFEST_PATH: "org.gnome.dfeet.json"
        RUNTIME_REPO: "https://nightly.gnome.org/gnome-nightly.flatpakrepo"
        # Replace with your application name, as written in the manifest
        FLATPAK_MODULE: "d-feet"
        APP_ID: "org.gnome.dfeet"
        BUILD_DIR: ".app"
        # Make sure to keep this in sync with the Flatpak manifest, all arguments
        # are passed except the config-args because we build it ourselves
        MESON_ARGS: |
          -Dtests=true

nightly:
    extends: '.publish_nightly'
    dependencies: ['flatpak']
    needs: ['flatpak']
